### ISSUE TITLE
Xcode / iOS Undefined symbol: _WebSocketAddSubprotocol

### ISSUE THREAD

**Issue by epmapps** [mikerochip/unity-websocket#11]
Hi, I am trying to build my unity app to iOS and receiving these errors when building in xcode:

<img width="269" alt="Screenshot 2023-11-27 at 12 01 09 PM" src="https://github.com/mikerochip/unity-websocket/assets/11800004/33713857-0649-4664-91d3-0ac5a72b15b1">

This is the only package that I am importing / using at the moment. Thanks

**Comment by epmapps** [comment]
I have imported the library correctly afict

<img width="567" alt="Screenshot 2023-11-27 at 7 06 44 PM" src="https://github.com/mikerochip/unity-websocket/assets/11800004/441cdb96-5346-44e9-996a-da758b0c90e1">
<img width="681" alt="Screenshot 2023-11-27 at 7 05 52 PM" src="https://github.com/mikerochip/unity-websocket/assets/11800004/b856df7c-b9f0-4730-9319-e670262e2222">

Am I missing something wrt deploying a unity project to iOS? I was able to deploy to the phone before adding this library.
Any help would be appreciated!

**Comment by mikerochip** [comment]
Hi there. Thanks for letting me know about the build errors, I see them as well and will fix them soon.

> networking file

What do you mean by networking file? I can't see your project, so I'm not sure.

> I removed this package and it worked. Reinstalled it and only uncommented top line: public WebSocketConnection _Connection; and it does not work... Only solution I see is to remake the project lol..

I'm not really sure what's going on with all this, but based on the small code snippet, it looks like you are copy/pasting the sample code from the readme; I would need to see more of the code to help.

**Comment by mikerochip** [comment]
Try again by updating to the latest: in your Unity project, open the package manager, click the update button on this library, then build and run on your devices. If it still doesn't work, then please open a new issue and post more of the code so I can help.

I've closed this issue due to fixing the build errors from the OP.
