### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by alters-mit** [mikerochip/unity-websocket#9]
I'm using Unity 2020.3.24. This is an old project and I can't upgrade the engine.

unity-websocket fails to compile to a WebGL build unless I replace lines like this:

```
console.log('[JSLIB WebSocket] Received message: ${ev.data}`);
```

to lines line this:

```
console.log("[JSLIB WebSocket] Received message: ${ev.data}");
```

in WebSocket.jslib

**Comment by mikerochip** [comment]
Hello. I think you might have some copy paste errors? Are you replacing the backticks with double quotes?

I recently bumped the minimum version to 2021.2 but I can take a look at downgrading back to 2019.3

**Comment by alters-mit** [comment]
Edited with better copy-pasting

**Comment by mikerochip** [comment]
Thanks for bringing up this issue. Other than [weird hacks](https://forum.unity.com/threads/case-1412113-builderror-osx-12-3-and-unity-2020-3-constant-build-errors.1255419/#post-8003132) I had to do to get my test project to build WebGL on Mac with Unity 2019.4, it was a pretty straightforward change to this package to support that version as the new minimum.
